[package]
name = "signal-tui"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.4"
crossterm = "0.29.0"
directories = "6.0.0"
hostname = "0.4.1"
ratatui = "0.29.0"
rusqlite = "0.35.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
